version: '3.7'

services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - inception

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - inception

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    expose:
      - "9000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - inception

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: '/home/${USER}/data/mariadb'
      o: bind

  wordpress:
    driver: local
    driver_opts:
      type: none
      device: '/home/${USER}/data/wordpress'
      o: bind

networks:
  inception:
    driver: bridge

